[package]
name = "duplikatd"
version = "0.1.0"
authors = ["Gustavo Noronha Silva <gustavo@noronha.dev.br>"]
edition = "2018"

[dependencies]
duplikat-types = { path = "../duplikat-types" }
serde = "1.0"
serde_json = "1.0"
vial = { version = "0.1.8", features = ["json_serde"] }